name: My Action
on:
    push:
        branches:
            - main
jobs:
    build-and-push-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to container registry
              run: docker login https://ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_KEY }}
            - name: Build and push image to registry
              run: docker buildx build --push -t ${{ secrets.DOCKER_TAG }} TA2/.
    deploy:
      runs-on: ubuntu-latest

      needs: build

      steps:
        - name: Lowercase the repo name
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
